plugins {
    id 'java'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'

    version = mod_version
    group = mod_group_id

    java.toolchain.languageVersion = JavaLanguageVersion.of(17)

    repositories {
        mavenCentral()
        maven {
            name = "MinecraftForge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "Iron's Maven"
            url = "https://code.redspace.io/releases"
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }
}
