# Gradle properties
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Mappings & Versions
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.234
neo_form_version=1.21.1-20240808.144430
loader_version_range=[1,)

# Mod Properties
mod_id=iron_spell_tweaker
mod_name=Iron's Spell Tweaker GUI
mod_license=MIT
mod_version=1.0.0
mod_group_id=dev.codex.ironspelltweaker
mod_authors=vivo9
mod_description=An intuitive GUI to tweak Iron's Spells 'n Spellbooks stats, cooldowns, mana costs, and rarities directly before starting the game.
