plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = project.neo_form_version

    parchment {
        mappingsVersion = project.parchment_mappings_version
        minecraftVersion = project.parchment_minecraft_version
    }
}

dependencies {
    compileOnly files("${rootProject.projectDir}/libs/irons_spellbooks-1.21.1-3.16.2.jar")
    compileOnly files("${rootProject.projectDir}/libs/irons_lib-1.21.1-2.1.0.jar")
    compileOnly files("${rootProject.projectDir}/libs/yet_another_config_lib_v3-3.8.2+1.21.1-neoforge.jar")
}
