modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="iron_spell_tweaker"
version="1.0.0"
displayName="Iron's Spell Tweaker GUI"
logoFile="icon.png"
authors="vivo9"
description='''
An intuitive GUI to tweak Iron's Spells 'n Spellbooks stats, cooldowns, mana costs, and rarities directly before starting the game.
'''

[[dependencies.iron_spell_tweaker]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.iron_spell_tweaker]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.iron_spell_tweaker]]
    modId="irons_spellbooks"
    type="required"
    versionRange="[1.21.1,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.iron_spell_tweaker]]
    modId="yet_another_config_lib_v3"
    type="optional"
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="CLIENT"
